#!/usr/bin/env bash

# Install Quality of Service files to operational directories

set -e

if [ $(id -u) -ne 0 ]; then
    echo "Root privileges are required for running $0."
    exit 1
fi

MY_DIR=$(dirname $0)
systemd='/etc/systemd/system/'
unit='qos.service'
sbin='/usr/local/sbin/'
script='qos'
sbinscript="$sbin/$script"

systemctl stop "$unit"

cp "$MY_DIR/$unit" "$systemd"
cp "$MY_DIR/$script" "$sbin"

chmod u+x "$sbinscript"

systemctl daemon-reload
systemctl start "$unit"
systemctl reenable "$unit"
