#!/usr/bin/env bash

function pause()
{
    /usr/bin/transmission-remote 9091 -as --alt-speed > /dev/null
}

function resume()
{
    /usr/bin/transmission-remote 9091 -AS --no-alt-speed > /dev/null
}

function start()
{
    on=false

    declare -a ignored=(
        192.168.0.50
        192.168.0.101
        192.168.0.104
        192.168.0.151
        192.168.0.200
    )

    while true; do
        hostsUp=false

        hosts=($(ssh markieta@192.168.0.1 "/sbin/arp -a" | cut -d "(" -f2 | cut -d ")" -f1))

        if [ ! -z "$(echo ${ignored[@]} ${ignored[@]} ${hosts[@]} | tr ' ' '\n' | sort | uniq -u)" ]; then
            hostsUp=true
        fi

        if [ "$hostsUp" = true ] ||
           [ "$(/usr/bin/wget -q --user admin --password admin 192.168.0.50/DI_S_.xml -O - | grep -co '0 Active Calls')" -ne 3 ] ||
           [ "$(/usr/bin/curl --data-binary '{ "jsonrpc": "2.0", "method": "XBMC.GetInfoBooleans", "params": { "booleans": ["System.IdleTime(599) "]}, "id": 1}' -H 'content-type: application/json;' http://kodi@localhost:8080/jsonrpc | jq .result[])" = false ]; then
            if [ "$on" = true ]; then
                pause
                on=false
            fi
            sleep 600
        else
            sleep 5
            on=true
            resume
        fi
    done
}

function stop()
{
    pause
    kill -s HUP $MAINPID
}

function restart()
{
    stop
    start
}

case "$1" in
    start|stop|restart|pause|resume) "$1" ;;
    *) echo $"Usage: $0 {start|stop|restart|pause|resume}"
esac
