#!/usr/bin/env bash

function pause()
{
    transmission-remote 192.168.0.2:9091 -N /root/.netrc --alt-speed > /dev/null 2>&1
}

function resume()
{
    transmission-remote 192.168.0.2:9091 -N /root/.netrc --no-alt-speed > /dev/null 2>&1
}

function start()
{
    on=false
    voipUp=true
    pause

    declare -a ignored=(
        192.168.0.0
        192.168.0.1
        192.168.0.2
        192.168.0.7
        192.168.0.50
        192.168.0.51
        192.168.0.52
        192.168.0.53
        192.168.0.54
        192.168.0.56
        192.168.0.57
        192.168.0.58
        192.168.0.59
        192.168.0.60
        192.168.0.64
        192.168.0.66
        192.168.0.67
        192.168.0.255
    )

    while true; do
        hostsUp=false

        fping -qg 192.168.0.0/24
        hosts=$(arp -an | grep -v 'incomplete' | cut -d "(" -f2 | cut -d ")" -f1 | grep "^192\.168\.0\.")

        if [ -n "$(echo ${ignored[@]} ${ignored[@]} ${hosts[@]} | tr ' ' '\n' | sort | uniq -u)" ]; then
            hostsUp=true
        fi

        voipStats=$(wget -q -t 1 -T 15 --user admin --password admin voip/PI_FXS_1_Stats.xml -O -)

        if [ "$hostsUp" = true ] ||
           [[ $(ip -all netns exec netstat -tapn | grep -w 64738 | grep ESTABLISHED) ]] ||
           [ "$(echo $voipStats | xmllint --xpath "string(//model/object/parameter/value/@current)" - )" = "Off Hook" ]; then
            if [ "$on" = true ]; then
                pause
                on=false
            fi
            sleep 600
        else
            sleep 5

            if [ "$on" = false ]; then
                on=true
                resume
            fi
        fi
    done
}

function stop()
{
    pause
    kill -s HUP $MAINPID
}

function restart()
{
    stop
    start
}

case "$1" in
    start|stop|restart|pause|resume) "$1" ;;
    *) echo $"Usage: $0 {start|stop|restart|pause|resume}"
esac
